/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Balazs
 */
public class ablak extends javax.swing.JFrame {

    Random r = new Random();
    int golyoHelye = r.nextInt(3 - 1 + 1) - 1;

    /**
     * Creates new form ablak
     */
    public ablak() {
        initComponents();
        setVisible(true);

        if (Files.exists(Paths.get("tipp.deb"))) {
            setTitle("A golyó a " + golyoHelye + ". számú pohár alatt van");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPohar1 = new javax.swing.JButton();
        btnPohar2 = new javax.swing.JButton();
        btnPohar3 = new javax.swing.JButton();
        lbVisszajelzes = new javax.swing.JLabel();
        ckbUjHely = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFajl = new javax.swing.JMenu();
        mnuUjJatek = new javax.swing.JMenuItem();
        mnuMentes = new javax.swing.JMenuItem();
        mnuBetoltes = new javax.swing.JMenuItem();
        mnuJatek = new javax.swing.JMenu();
        mnu3Pohar = new javax.swing.JMenuItem();
        mnu4Pohar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPohar1.setText("Pohár1");
        btnPohar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar1ActionPerformed(evt);
            }
        });

        btnPohar2.setText("Pohár 2");
        btnPohar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar2ActionPerformed(evt);
            }
        });

        btnPohar3.setText("Pohár3");
        btnPohar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar3ActionPerformed(evt);
            }
        });

        lbVisszajelzes.setText("Visszajelzés");

        ckbUjHely.setText("Tippelésenként új helyre kerüljön a golyó");

        mnuFajl.setText("Fájl");

        mnuUjJatek.setText("Új játék");
        mnuUjJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUjJatekActionPerformed(evt);
            }
        });
        mnuFajl.add(mnuUjJatek);

        mnuMentes.setText("Mentés");
        mnuMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMentesActionPerformed(evt);
            }
        });
        mnuFajl.add(mnuMentes);

        mnuBetoltes.setText("Betöltés");
        mnuBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBetoltesActionPerformed(evt);
            }
        });
        mnuFajl.add(mnuBetoltes);

        jMenuBar1.add(mnuFajl);

        mnuJatek.setText("Játék");

        mnu3Pohar.setText("3 pohár");
        mnu3Pohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu3PoharActionPerformed(evt);
            }
        });
        mnuJatek.add(mnu3Pohar);

        mnu4Pohar.setText("4 pohár");
        mnu4Pohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu4PoharActionPerformed(evt);
            }
        });
        mnuJatek.add(mnu4Pohar);

        jMenuBar1.add(mnuJatek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbUjHely)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPohar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPohar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPohar3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ckbUjHely)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPohar1)
                    .addComponent(btnPohar2)
                    .addComponent(btnPohar3))
                .addGap(54, 54, 54)
                .addComponent(lbVisszajelzes)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu4PoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu4PoharActionPerformed
        //felugró figyelmeztetés
        lbVisszajelzes.setText("Ez a funkció egyelőre nem elérhető!");
    }//GEN-LAST:event_mnu4PoharActionPerformed

    private void mnu3PoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu3PoharActionPerformed


    }//GEN-LAST:event_mnu3PoharActionPerformed

    private void btnPohar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar1ActionPerformed
        if (golyoHelye == 1) {
            lbVisszajelzes.setText("Sikeres tipp!");
        } else {
            lbVisszajelzes.setText("Nem itt van!");
            if (ckbUjHely.isSelected()) {
                golyoHelye = r.nextInt((3 - 1) + 1) + 1;
            }
        }
    }//GEN-LAST:event_btnPohar1ActionPerformed

    private void btnPohar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar2ActionPerformed
        if (golyoHelye == 2) {
            lbVisszajelzes.setText("Sikeres tipp!");
        } else {
            lbVisszajelzes.setText("Nem itt van!");
            if (ckbUjHely.isSelected()) {
                golyoHelye = r.nextInt(3 - 1 + 1) - 1;
            }
        }
    }//GEN-LAST:event_btnPohar2ActionPerformed

    private void btnPohar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar3ActionPerformed
        if (golyoHelye == 3) {
            lbVisszajelzes.setText("Sikeres tipp!");
        } else {
            lbVisszajelzes.setText("Nem itt van!");
            if (ckbUjHely.isSelected()) {
                golyoHelye = r.nextInt(3 - 1 + 1) - 1;
            }
        }
    }//GEN-LAST:event_btnPohar3ActionPerformed

    private void mnuUjJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUjJatekActionPerformed
        lbVisszajelzes.setText("Visszajelzés");
        ckbUjHely.setSelected(false);
        golyoHelye = r.nextInt(3 - 1 + 1) - 1;
    }//GEN-LAST:event_mnuUjJatekActionPerformed

    private void mnuMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMentesActionPerformed
        RandomAccessFile raf;
        ArrayList<String> adatok = new ArrayList<>();
        if (mnu3Pohar.isSelected()) {
            adatok.add("3 pohár");
        } else if (mnu4Pohar.isSelected()) {
            adatok.add("4 pohár");
        }
        adatok.add(String.valueOf(golyoHelye));
        if (lbVisszajelzes.getText().equals("Sikeres tipp!")) {
            adatok.add("Nyert");
        } else if (lbVisszajelzes.getText().equals("Nem itt van!")) {
            adatok.add("Vesztett");
        } else {
            adatok.add("Nem játszott");
        }
        if (ckbUjHely.isSelected()) {
            adatok.add("Mindig újra kever");
        } else {
            adatok.add("Nem kever");
        }

        try {
            raf = new RandomAccessFile("config.txt", "rw");
            for (String s : adatok) {
                raf.writeBytes(s + "\n");
            }

            raf.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mnuMentesActionPerformed

    private void mnuBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBetoltesActionPerformed
        try {
            if (Files.exists(Paths.get("tipp.deb"))) {
                setTitle("A golyó a " + golyoHelye + ". számú pohár alatt van");
            }
            List<String> sorok = Files.readAllLines(Paths.get("config.txt"));
            List<Adatok> adatLista = new ArrayList<>();
            for (int i = 1; i < sorok.size(); i++) {
                String sor = sorok.get(i);
                adatLista.add(new Adatok(sor));
            }
            for (Adatok adat : adatLista) {
                if (adat.getJatekMod().equals("4 pohár")) {
                    lbVisszajelzes.setText("Ez a funkció egyelőre nem elérhető!");
                }
                golyoHelye = adat.getGolyoHelye();
                if (adat.getAllapot().equals("Vesztett")) {
                    lbVisszajelzes.setText("Nem itt van!");
                } else if (adat.getAllapot().equals("Nyert")) {
                    lbVisszajelzes.setText("Sikeres tipp!");
                }
                if (adat.getKeveres().equals("Mindig újra kever")) {
                    ckbUjHely.setSelected(true);
                } else {
                    ckbUjHely.setSelected(false);
                }

            }
        } catch (IOException ex) {
            Logger.getLogger(ablak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuBetoltesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPohar1;
    private javax.swing.JButton btnPohar2;
    private javax.swing.JButton btnPohar3;
    private javax.swing.JCheckBox ckbUjHely;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbVisszajelzes;
    private javax.swing.JMenuItem mnu3Pohar;
    private javax.swing.JMenuItem mnu4Pohar;
    private javax.swing.JMenuItem mnuBetoltes;
    private javax.swing.JMenu mnuFajl;
    private javax.swing.JMenu mnuJatek;
    private javax.swing.JMenuItem mnuMentes;
    private javax.swing.JMenuItem mnuUjJatek;
    // End of variables declaration//GEN-END:variables
}
