/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

/**
 *
 * @author Balazs
 */
public class ablak extends javax.swing.JFrame {

    /**
     * Creates new form ablak
     */
    public ablak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPohar1 = new javax.swing.JButton();
        btnPohar2 = new javax.swing.JButton();
        btnPohar3 = new javax.swing.JButton();
        lbVisszajelzes = new javax.swing.JLabel();
        ckbUjHely = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFajl = new javax.swing.JMenu();
        mnuUjJatek = new javax.swing.JMenuItem();
        mnuMentes = new javax.swing.JMenuItem();
        mnuBetoltes = new javax.swing.JMenuItem();
        mnuJatek = new javax.swing.JMenu();
        mnu3Pohar = new javax.swing.JMenuItem();
        mnu4Pohar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPohar1.setText("Pohár1");

        btnPohar2.setText("Pohár 2");

        btnPohar3.setText("Pohár3");

        lbVisszajelzes.setText("Visszajelzés");

        ckbUjHely.setText("Tippelésenként új helyre kerüljön a golyó");

        mnuFajl.setText("Fájl");

        mnuUjJatek.setText("Új játék");
        mnuFajl.add(mnuUjJatek);

        mnuMentes.setText("Mentés");
        mnuFajl.add(mnuMentes);

        mnuBetoltes.setText("Betöltés");
        mnuFajl.add(mnuBetoltes);

        jMenuBar1.add(mnuFajl);

        mnuJatek.setText("Játék");

        mnu3Pohar.setText("3 pohár");
        mnuJatek.add(mnu3Pohar);

        mnu4Pohar.setText("4 pohár");
        mnuJatek.add(mnu4Pohar);

        jMenuBar1.add(mnuJatek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPohar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnPohar2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnPohar3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckbUjHely))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ckbUjHely)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPohar1)
                    .addComponent(btnPohar2)
                    .addComponent(btnPohar3))
                .addGap(51, 51, 51)
                .addComponent(lbVisszajelzes)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPohar1;
    private javax.swing.JButton btnPohar2;
    private javax.swing.JButton btnPohar3;
    private javax.swing.JCheckBox ckbUjHely;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbVisszajelzes;
    private javax.swing.JMenuItem mnu3Pohar;
    private javax.swing.JMenuItem mnu4Pohar;
    private javax.swing.JMenuItem mnuBetoltes;
    private javax.swing.JMenu mnuFajl;
    private javax.swing.JMenu mnuJatek;
    private javax.swing.JMenuItem mnuMentes;
    private javax.swing.JMenuItem mnuUjJatek;
    // End of variables declaration//GEN-END:variables
}
